package com.ruialmeida.quarentilograms.features.authenticated.viewmodel

import com.ruialmeida.quarentilograms.shared.viewmodel.BaseDataBindingViewModel

class AuthenticatedActivityViewModel : BaseDataBindingViewModel()